language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
before_install: "mkdir -p $HOME/.distlib && sudo chown -R travis:travis $HOME/.distlib || true"
before_script: "whoami && ls -ld $HOME/.distlib"
script: "PYTHONHASHSEED=0 python setup.py test"
